### PR TITLE
Prevent corrupt lfs files during transfer

### LINKED ISSUE #2043: LFS is giving incorrect hash
I'm getting an error when cloning a repository:
Downloading Deployment Materials/Data/some path/some file.xml (11 MB)
Error downloading object: Deployment Materials/Data/some path/some file.xml (e7bdc0d): Smudge error: Error downloading Deployment Materials/Data/some path/some file.xml (e7bdc0d7851c3fe6bb43d8836a27f1d110504b5cc9ef756e348ed156f1cd4841): expected OID e7bdc0d7851c3fe6bb43d8836a27f1d110504b5cc9ef756e348ed156f1cd4841, got 98a84bfe44be9dae80c906c82ba555f93e8e140b8d31769e02bcd6175238e718 after 2732544 bytes written
Errors logged to C:\Users\Itais\Documents\unilogic3\.git\lfs\logs\20220522T134651.7824827.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
Filtering content:  99% (3307/3337), 990.31 MiB | 8.89 MiB/s 

Later on, when sourcetree is requesting to download the lfs, I get the following error (30 files total fail on lfs)

image

This is a repository I've created only few days ago.
The Non-LFS files are stored in BitBucket, and the LFS files are on a local repository, running SCM Manager 2.34.0

I did nothing special. If I cannot trust the LFS, then it is useless.

### PR DESCRIPTION
**Pull request by eheimbuch**
## Proposed changes

Validate lfs file checksum to ensure that the file was transferred successfully. If an error occur delete the blob to prevent corrupt files inside the storage.

Fixes #2043 

### Your checklist for this pull request

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

**Contributor**:
- [x] PR is well described and the description can be used as a commit message on squash
- [x] Related issues linked to PR if existing and labels set
- [ ] New code is covered with unit tests
- [ ] New/updated ui components are tested inside the storybook (module ui-components only) 
- [x] [Changelog entry file](https://github.com/scm-manager/changelog#changelog-entry-files) created in `gradle/changelog`
- [ ] Feature has been tested with different permissions
- [ ] Documentation updated (only necessary for new features or changed behaviour)

**Reviewer**:
- [x] The clean code principles are respected ([CleanCode](https://clean-code-developer.com/virtues/))
- [x] All new code/logic is implemented on the right spot / "Should this be done here?"
- [ ] UI changes fits into the layout
- [ ] The UI views / components are responsive (mobile views)
- [ ] Correct translations are available

### Checklist for branch merge request (not required for forks)

- [x] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [x] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

### CODE REVIEW

File: scm-plugins/scm-git-plugin/src/main/java/sonia/scm/web/lfs/servlet/ScmFileTransferServlet.java [hunk 1]
```diff
@@ -269,22 +272,27 @@ private void writeBlobIntoResponse(Blob savedBlob, HttpServletResponse response)
...
+      blobStore.remove(blob);
       sendErrorAndLog(response, HttpStatus.SC_BAD_REQUEST, ex);
     }
+  }
 
-
+  private void validateStoredFile(Blob blob, DigestInputStream requestInputStream) throws IOException {
+    byte[] digest = requestInputStream.getMessageDigest().digest();
+    if (!blob.getId().equals(Hex.encodeHexString(digest, true))) {
+      throw new IOException("Transferred file seems to be corrupt");
```
Comment (pfeuffer) [inline scm-plugins/scm-git-plugin/src/main/java/sonia/scm/web/lfs/servlet/ScmFileTransferServlet.java:294]: I would log both hashes, expected and computed, here

File: gradle/changelog/lfs_corrupt_files.yaml [hunk 2]
```diff
@@ -0,0 +1,2 @@
+- type: fixed
+  description: Validate lfs files after transfer and cleanup corrupt files ([#2068](https://github.com/scm-manager/scm-manager/pull/2068))
```
Comment (pfeuffer) [inline gradle/changelog/lfs_corrupt_files.yaml:2]:
```suggestion
  description: Validate lfs files after upload and discard corrupt files ([#2068](https://github.com/scm-manager/scm-manager/pull/2068))
```

**Review by pfeuffer — APPROVED** [review]
Just two small remarks 👍🏽
